export const arr = [
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1000",
        price: "200",
    },

    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1400",
        price: "700",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },

    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },

    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },

    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },

    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "1280",
        price: "900",
    },
    {
        images: "https://via.placeholder.com/500",
        pName: "Midi Off Shoulder Ruched Dress",
        originalPrice: "100000",
        price: "10000",
    },
]